# Generated by Django 2.2.1 on 2019-05-19 13:10

import bins.tokens
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=functools.partial(bins.tokens.generate_token, *(64,), **{}), max_length=64)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('max_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('current_weight', models.FloatField(default=0.0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
