# Generated by Django 2.2.1 on 2019-05-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='fullness',
            field=models.FloatField(default=0.0),
        ),
    ]
